# Generated by Django 4.2.4 on 2023-08-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_bills_facilities_menutype_roomtype_service_room_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bills',
            new_name='Bill',
        ),
    ]
